# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('passwd', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
